-- ============================================================================
-- BANCO BANQUITO V2 - CORE ACCOUNT SERVICE
-- Modelo fisico MySQL 8.4 LTS
-- Base: banquito_core_account_db
-- Proposito: cuentas, saldos, estados, transacciones, reservas de pagos masivos,
-- instrucciones recibidas del Switch, reversos y outbox.
-- ============================================================================
CREATE DATABASE IF NOT EXISTS banquito_core_account_db
  DEFAULT CHARACTER SET utf8mb4
  DEFAULT COLLATE utf8mb4_unicode_ci;
USE banquito_core_account_db;

SET FOREIGN_KEY_CHECKS = 0;
DROP VIEW IF EXISTS V_SALDO_CUENTA_RESUMEN;
DROP TABLE IF EXISTS OUTBOX_EVENT;
DROP TABLE IF EXISTS AUDITORIA_ACCOUNT_EVENTO;
DROP TABLE IF EXISTS HISTORIAL_ESTADO_CUENTA;
DROP TABLE IF EXISTS BLOQUEO_CUENTA;
DROP TABLE IF EXISTS MOVIMIENTO_RESERVA_PAGO;
DROP TABLE IF EXISTS TRANSACCION_CUENTA;
DROP TABLE IF EXISTS INSTRUCCION_PAGO_MASIVO_CORE;
DROP TABLE IF EXISTS RESERVA_PAGO_MASIVO;
DROP TABLE IF EXISTS CUENTA;
SET FOREIGN_KEY_CHECKS = 1;

CREATE TABLE CUENTA (
  ID BIGINT AUTO_INCREMENT NOT NULL,
  UUID_CUENTA CHAR(36) NOT NULL,
  NUMERO_CUENTA VARCHAR(24) NOT NULL,
  UUID_CLIENTE CHAR(36) NOT NULL COMMENT 'Referencia a customer-service; sin FK cruzada',
  IDENTIFICACION_TITULAR VARCHAR(20) NOT NULL,
  NOMBRE_TITULAR_REFERENCIA VARCHAR(180) NOT NULL,
  CODIGO_SUCURSAL VARCHAR(10) NOT NULL,
  CODIGO_SUBTIPO_CUENTA VARCHAR(30) NOT NULL,
  ESTADO VARCHAR(15) NOT NULL DEFAULT 'ACTIVA',
  SALDO_CONTABLE DECIMAL(19,2) NOT NULL DEFAULT 0.00,
  SALDO_DISPONIBLE DECIMAL(19,2) NOT NULL DEFAULT 0.00,
  MONTO_RETENIDO DECIMAL(19,2) NOT NULL DEFAULT 0.00,
  PERMITE_SOBREGIRO TINYINT(1) NOT NULL DEFAULT 0,
  LIMITE_SOBREGIRO DECIMAL(19,2) NOT NULL DEFAULT 0.00,
  ES_CUENTA_MATRIZ_PAGOS TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'Cuenta habilitada como matriz de pagos masivos',
  ES_CUENTA_FAVORITA_PAGOS TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'Cuenta por defecto para cargas SFTP u origen no interactivo',
  ALIAS_OPERATIVO VARCHAR(80) NULL COMMENT 'Alias visible para seleccion operativa',
  PROPOSITO_CUENTA VARCHAR(20) NOT NULL DEFAULT 'GENERAL' COMMENT 'GENERAL, OPERATIVA, NOMINA, IMPUESTOS, PAGOS_MASIVOS',
  CUENTA_FAVORITA_CLIENTE_KEY CHAR(36) GENERATED ALWAYS AS (CASE WHEN ES_CUENTA_FAVORITA_PAGOS = 1 THEN UUID_CLIENTE ELSE NULL END) STORED,
  FECHA_APERTURA DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FECHA_ACTUALIZACION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  VERSION INT NOT NULL DEFAULT 0,
  CONSTRAINT PK_CUENTA PRIMARY KEY (ID),
  CONSTRAINT UK_CUENTA_UUID UNIQUE (UUID_CUENTA),
  CONSTRAINT UK_CUENTA_NUMERO UNIQUE (NUMERO_CUENTA),
  CONSTRAINT UK_CUENTA_FAVORITA_CLIENTE UNIQUE (CUENTA_FAVORITA_CLIENTE_KEY),
  CONSTRAINT CK_CUENTA_ESTADO CHECK (ESTADO IN ('ACTIVA','INACTIVA','BLOQUEADA','SUSPENDIDA','CERRADA')),
  CONSTRAINT CK_CUENTA_SALDOS CHECK (SALDO_CONTABLE >= -LIMITE_SOBREGIRO AND SALDO_DISPONIBLE >= -LIMITE_SOBREGIRO AND MONTO_RETENIDO >= 0),
  CONSTRAINT CK_CUENTA_SOBREGIRO CHECK ((PERMITE_SOBREGIRO = 1 AND LIMITE_SOBREGIRO >= 0) OR (PERMITE_SOBREGIRO = 0 AND LIMITE_SOBREGIRO = 0)),
  CONSTRAINT CK_CUENTA_PROPOSITO CHECK (PROPOSITO_CUENTA IN ('GENERAL','OPERATIVA','NOMINA','IMPUESTOS','PAGOS_MASIVOS'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Cuentas de clientes y saldos';

CREATE TABLE RESERVA_PAGO_MASIVO (
  ID BIGINT AUTO_INCREMENT NOT NULL,
  UUID_RESERVA CHAR(36) NOT NULL,
  BATCH_ID_EXTERNO VARCHAR(80) NOT NULL COMMENT 'ID de lote del Switch; sin FK cruzada',
  UUID_CORRELACION CHAR(36) NOT NULL,
  UUID_CLIENTE_EMPRESA CHAR(36) NOT NULL,
  CUENTA_MATRIZ_ID BIGINT NOT NULL,
  NUMERO_CUENTA_MATRIZ VARCHAR(24) NOT NULL,
  CANAL_ORIGEN VARCHAR(20) NOT NULL DEFAULT 'SWITCH_API',
  MONTO_TOTAL_LOTE DECIMAL(19,2) NOT NULL,
  MONTO_COMISION DECIMAL(19,2) NOT NULL DEFAULT 0.00,
  MONTO_RESERVADO DECIMAL(19,2) NOT NULL,
  MONTO_CONSUMIDO_ONUS DECIMAL(19,2) NOT NULL DEFAULT 0.00,
  MONTO_CONSUMIDO_OFFUS DECIMAL(19,2) NOT NULL DEFAULT 0.00,
  MONTO_LIBERADO DECIMAL(19,2) NOT NULL DEFAULT 0.00,
  ASIENTO_RESERVA_UUID CHAR(36) NULL,
  ESTADO VARCHAR(25) NOT NULL DEFAULT 'CREADA',
  FECHA_CONTABLE DATE NOT NULL,
  FECHA_CREACION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FECHA_ACTUALIZACION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  VERSION INT NOT NULL DEFAULT 0,
  CONSTRAINT PK_RESERVA_PM PRIMARY KEY (ID),
  CONSTRAINT UK_RESERVA_PM_UUID UNIQUE (UUID_RESERVA),
  CONSTRAINT UK_RESERVA_PM_BATCH UNIQUE (BATCH_ID_EXTERNO),
  CONSTRAINT FK_RESERVA_CUENTA FOREIGN KEY (CUENTA_MATRIZ_ID) REFERENCES CUENTA(ID) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT CK_RESERVA_CANAL CHECK (CANAL_ORIGEN IN ('SWITCH_WEB','SWITCH_SFTP','SWITCH_API')),
  CONSTRAINT CK_RESERVA_ESTADO CHECK (ESTADO IN ('CREADA','ACTIVA','CONSUMIDA_PARCIAL','CONSUMIDA_TOTAL','LIBERADA','REVERSADA','FALLIDA')),
  CONSTRAINT CK_RESERVA_MONTOS CHECK (MONTO_TOTAL_LOTE >= 0 AND MONTO_COMISION >= 0 AND MONTO_RESERVADO >= 0 AND MONTO_CONSUMIDO_ONUS >= 0 AND MONTO_CONSUMIDO_OFFUS >= 0 AND MONTO_LIBERADO >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Reserva/fondeo global de lote de pagos masivos';

CREATE TABLE INSTRUCCION_PAGO_MASIVO_CORE (
  ID BIGINT AUTO_INCREMENT NOT NULL,
  UUID_INSTRUCCION CHAR(36) NOT NULL,
  RESERVA_PAGO_MASIVO_ID BIGINT NOT NULL,
  BATCH_ID_EXTERNO VARCHAR(80) NOT NULL,
  PAYMENT_LINE_UUID CHAR(36) NOT NULL,
  UUID_CORRELACION CHAR(36) NOT NULL,
  TIPO_DESTINO VARCHAR(10) NOT NULL COMMENT 'ON_US u OFF_US',
  ROUTING_CODE_DESTINO VARCHAR(20) NOT NULL,
  CUENTA_DESTINO_ID BIGINT NULL,
  NUMERO_CUENTA_DESTINO VARCHAR(24) NULL,
  CUENTA_DESTINO_EXTERNA VARCHAR(34) NULL,
  IDENTIFICACION_BENEFICIARIO VARCHAR(20) NOT NULL,
  NOMBRE_BENEFICIARIO VARCHAR(180) NOT NULL,
  EMAIL_BENEFICIARIO VARCHAR(160) NULL,
  CONCEPTO VARCHAR(250) NULL,
  MONTO DECIMAL(19,2) NOT NULL,
  ESTADO VARCHAR(25) NOT NULL DEFAULT 'RECIBIDA',
  MOTIVO_RECHAZO VARCHAR(300) NULL,
  FECHA_CONTABLE DATE NOT NULL,
  FECHA_CREACION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FECHA_ACTUALIZACION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  VERSION INT NOT NULL DEFAULT 0,
  CONSTRAINT PK_INSTRUCCION_PM_CORE PRIMARY KEY (ID),
  CONSTRAINT UK_INSTRUCCION_PM_UUID UNIQUE (UUID_INSTRUCCION),
  CONSTRAINT UK_INSTRUCCION_PM_LINEA_GLOBAL UNIQUE (PAYMENT_LINE_UUID),
  CONSTRAINT UK_INSTRUCCION_PM_RESERVA_LINEA UNIQUE (RESERVA_PAGO_MASIVO_ID, PAYMENT_LINE_UUID),
  CONSTRAINT FK_INSTRUCCION_RESERVA FOREIGN KEY (RESERVA_PAGO_MASIVO_ID) REFERENCES RESERVA_PAGO_MASIVO(ID) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT FK_INSTRUCCION_CUENTA_DESTINO FOREIGN KEY (CUENTA_DESTINO_ID) REFERENCES CUENTA(ID) ON UPDATE RESTRICT ON DELETE SET NULL,
  CONSTRAINT CK_INSTRUCCION_DESTINO CHECK (TIPO_DESTINO IN ('ON_US','OFF_US')),
  CONSTRAINT CK_INSTRUCCION_ESTADO CHECK (ESTADO IN ('RECIBIDA','VALIDADA','EJECUTADA','RECHAZADA','REVERSADA')),
  CONSTRAINT CK_INSTRUCCION_MONTO CHECK (MONTO > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Instrucciones individuales de pago masivo recibidas desde Switch';

CREATE TABLE TRANSACCION_CUENTA (
  ID BIGINT AUTO_INCREMENT NOT NULL,
  UUID_TRANSACCION CHAR(36) NOT NULL,
  UUID_CORRELACION CHAR(36) NOT NULL,
  CUENTA_ID BIGINT NOT NULL,
  CODIGO_SUBTIPO_TRANSACCION VARCHAR(40) NOT NULL,
  ASIENTO_CONTABLE_UUID CHAR(36) NULL,
  RESERVA_PAGO_MASIVO_ID BIGINT NULL,
  INSTRUCCION_PAGO_CORE_ID BIGINT NULL,
  TRANSACCION_REVERSADA_ID BIGINT NULL,
  FECHA_CONTABLE DATE NOT NULL,
  TIMESTAMP_TRANSACCION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  TIPO_MOVIMIENTO VARCHAR(10) NOT NULL,
  MONTO DECIMAL(19,2) NOT NULL,
  SALDO_CONTABLE_ANTERIOR DECIMAL(19,2) NOT NULL,
  SALDO_CONTABLE_RESULTANTE DECIMAL(19,2) NOT NULL,
  SALDO_DISPONIBLE_RESULTANTE DECIMAL(19,2) NOT NULL,
  ESTADO VARCHAR(20) NOT NULL DEFAULT 'APLICADA',
  CANAL_ORIGEN VARCHAR(30) NOT NULL,
  REFERENCIA_EXTERNA VARCHAR(120) NULL,
  NUMERO_COMPROBANTE VARCHAR(80) NULL,
  UUID_DOCUMENTO_COMPROBANTE CHAR(36) NULL COMMENT 'Referencia a document-service/MongoDB',
  FECHA_CREACION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  VERSION INT NOT NULL DEFAULT 0,
  CONSTRAINT PK_TRANSACCION_CUENTA PRIMARY KEY (ID),
  CONSTRAINT UK_TRANSACCION_UUID UNIQUE (UUID_TRANSACCION),
  CONSTRAINT UK_TRANSACCION_IDEMPOTENCIA_DIA UNIQUE (CUENTA_ID, UUID_TRANSACCION, FECHA_CONTABLE),
  CONSTRAINT FK_TX_CUENTA FOREIGN KEY (CUENTA_ID) REFERENCES CUENTA(ID) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT FK_TX_RESERVA FOREIGN KEY (RESERVA_PAGO_MASIVO_ID) REFERENCES RESERVA_PAGO_MASIVO(ID) ON UPDATE RESTRICT ON DELETE SET NULL,
  CONSTRAINT FK_TX_INSTRUCCION FOREIGN KEY (INSTRUCCION_PAGO_CORE_ID) REFERENCES INSTRUCCION_PAGO_MASIVO_CORE(ID) ON UPDATE RESTRICT ON DELETE SET NULL,
  CONSTRAINT FK_TX_REVERSADA FOREIGN KEY (TRANSACCION_REVERSADA_ID) REFERENCES TRANSACCION_CUENTA(ID) ON UPDATE RESTRICT ON DELETE SET NULL,
  CONSTRAINT CK_TX_TIPO CHECK (TIPO_MOVIMIENTO IN ('DEBITO','CREDITO')),
  CONSTRAINT CK_TX_ESTADO CHECK (ESTADO IN ('APLICADA','RECHAZADA','REVERSADA','COMPENSADA','PENDIENTE_CONTABLE')),
  CONSTRAINT CK_TX_CANAL CHECK (CANAL_ORIGEN IN ('VENTANILLA','BANCA_WEB','SWITCH','ATM','CORE_INTERNO')),
  CONSTRAINT CK_TX_MONTO CHECK (MONTO > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Bitacora inmutable de movimientos de cuenta';

CREATE TABLE MOVIMIENTO_RESERVA_PAGO (
  ID BIGINT AUTO_INCREMENT NOT NULL,
  UUID_MOVIMIENTO CHAR(36) NOT NULL,
  RESERVA_PAGO_MASIVO_ID BIGINT NOT NULL,
  INSTRUCCION_PAGO_CORE_ID BIGINT NULL,
  TRANSACCION_CUENTA_ID BIGINT NULL,
  ASIENTO_CONTABLE_UUID CHAR(36) NULL,
  PAYMENT_LINE_UUID CHAR(36) NULL,
  TIPO_MOVIMIENTO VARCHAR(30) NOT NULL,
  MONTO DECIMAL(19,2) NOT NULL,
  ESTADO VARCHAR(20) NOT NULL DEFAULT 'APLICADO',
  FECHA_CONTABLE DATE NOT NULL,
  FECHA_CREACION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT PK_MOV_RESERVA PRIMARY KEY (ID),
  CONSTRAINT UK_MOV_RESERVA_UUID UNIQUE (UUID_MOVIMIENTO),
  CONSTRAINT FK_MOV_RESERVA FOREIGN KEY (RESERVA_PAGO_MASIVO_ID) REFERENCES RESERVA_PAGO_MASIVO(ID) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT FK_MOV_INSTRUCCION FOREIGN KEY (INSTRUCCION_PAGO_CORE_ID) REFERENCES INSTRUCCION_PAGO_MASIVO_CORE(ID) ON UPDATE RESTRICT ON DELETE SET NULL,
  CONSTRAINT FK_MOV_TX FOREIGN KEY (TRANSACCION_CUENTA_ID) REFERENCES TRANSACCION_CUENTA(ID) ON UPDATE RESTRICT ON DELETE SET NULL,
  CONSTRAINT CK_MOV_RESERVA_TIPO CHECK (TIPO_MOVIMIENTO IN ('RESERVA_INICIAL','CONSUMO_ONUS','CONSUMO_OFFUS','LIBERACION_SOBRANTE','REVERSO','COMISION')),
  CONSTRAINT CK_MOV_RESERVA_ESTADO CHECK (ESTADO IN ('APLICADO','RECHAZADO','REVERSADO')),
  CONSTRAINT CK_MOV_RESERVA_MONTO CHECK (MONTO >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Movimientos de consumo/liberacion/reverso sobre reservas';

CREATE TABLE BLOQUEO_CUENTA (
  ID BIGINT AUTO_INCREMENT NOT NULL,
  UUID_BLOQUEO CHAR(36) NOT NULL,
  CUENTA_ID BIGINT NOT NULL,
  MONTO_BLOQUEADO DECIMAL(19,2) NOT NULL,
  MOTIVO VARCHAR(300) NOT NULL,
  AUTORIDAD_ORDENANTE VARCHAR(150) NULL,
  ESTADO VARCHAR(15) NOT NULL DEFAULT 'ACTIVO',
  UUID_USUARIO_CORE CHAR(36) NULL,
  FECHA_BLOQUEO DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FECHA_LIBERACION DATETIME NULL,
  VERSION INT NOT NULL DEFAULT 0,
  CONSTRAINT PK_BLOQUEO_CUENTA PRIMARY KEY (ID),
  CONSTRAINT UK_BLOQUEO_UUID UNIQUE (UUID_BLOQUEO),
  CONSTRAINT FK_BLOQUEO_CUENTA FOREIGN KEY (CUENTA_ID) REFERENCES CUENTA(ID) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT CK_BLOQUEO_ESTADO CHECK (ESTADO IN ('ACTIVO','LIBERADO','REVOCADO')),
  CONSTRAINT CK_BLOQUEO_MONTO CHECK (MONTO_BLOQUEADO > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Bloqueos/retenciones sobre cuentas';

CREATE TABLE HISTORIAL_ESTADO_CUENTA (
  ID BIGINT AUTO_INCREMENT NOT NULL,
  CUENTA_ID BIGINT NOT NULL,
  ESTADO_ANTERIOR VARCHAR(15) NOT NULL,
  ESTADO_NUEVO VARCHAR(15) NOT NULL,
  MOTIVO_CAMBIO VARCHAR(300) NOT NULL,
  UUID_USUARIO_CORE CHAR(36) NULL,
  FECHA_CAMBIO DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT PK_HIST_ESTADO_CUENTA PRIMARY KEY (ID),
  CONSTRAINT FK_HIST_ESTADO_CUENTA FOREIGN KEY (CUENTA_ID) REFERENCES CUENTA(ID) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT CK_HIST_ESTADOS CHECK (ESTADO_ANTERIOR IN ('ACTIVA','INACTIVA','BLOQUEADA','SUSPENDIDA','CERRADA') AND ESTADO_NUEVO IN ('ACTIVA','INACTIVA','BLOQUEADA','SUSPENDIDA','CERRADA'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Historial de cambios de estado de cuenta';

CREATE TABLE AUDITORIA_ACCOUNT_EVENTO (
  ID BIGINT AUTO_INCREMENT NOT NULL,
  UUID_CORRELACION CHAR(36) NULL,
  UUID_USUARIO CHAR(36) NULL,
  UUID_API_CLIENT CHAR(36) NULL,
  SCOPE_USADO VARCHAR(120) NULL,
  MODULO VARCHAR(60) NOT NULL,
  ACCION VARCHAR(80) NOT NULL,
  ENTIDAD VARCHAR(80) NOT NULL,
  ENTIDAD_ID VARCHAR(80) NULL,
  RESULTADO VARCHAR(15) NOT NULL,
  CANAL_ORIGEN VARCHAR(30) NULL,
  IP_ORIGEN VARCHAR(45) NULL,
  DETALLE_JSON JSON NULL,
  FECHA_EVENTO DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT PK_AUDITORIA_ACCOUNT PRIMARY KEY (ID),
  CONSTRAINT CK_AUDITORIA_ACCOUNT_RESULTADO CHECK (RESULTADO IN ('OK','ERROR','DENEGADO'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Auditoria local de account-service';

CREATE TABLE REGISTRO_IDEMPOTENCIA (
  ID BIGINT AUTO_INCREMENT NOT NULL,
  UUID_REGISTRO CHAR(36) NOT NULL,
  ACTOR_UUID VARCHAR(80) NOT NULL,
  TIPO_OPERACION VARCHAR(60) NOT NULL,
  CLAVE_IDEMPOTENCIA VARCHAR(120) NOT NULL,
  HASH_SOLICITUD CHAR(64) NOT NULL,
  UUID_CORRELACION CHAR(36) NULL,
  ESTADO VARCHAR(20) NOT NULL DEFAULT 'EN_PROCESO',
  HTTP_STATUS INT NULL,
  RESPUESTA_JSON JSON NULL,
  ERROR_CODIGO VARCHAR(80) NULL,
  FECHA_CREACION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FECHA_ACTUALIZACION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FECHA_EXPIRACION DATETIME NOT NULL,
  VERSION INT NOT NULL DEFAULT 0,
  CONSTRAINT PK_REGISTRO_IDEMPOTENCIA PRIMARY KEY (ID),
  CONSTRAINT UK_IDEMPOTENCIA_UUID UNIQUE (UUID_REGISTRO),
  CONSTRAINT UK_IDEMPOTENCIA_ACTOR_OPERACION_CLAVE UNIQUE (ACTOR_UUID, TIPO_OPERACION, CLAVE_IDEMPOTENCIA),
  CONSTRAINT CK_IDEMPOTENCIA_ESTADO CHECK (ESTADO IN ('EN_PROCESO','COMPLETADA','FALLIDA'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Control persistente de idempotencia para operaciones monetarias HTTP';

CREATE TABLE OUTBOX_EVENT (
  ID BIGINT AUTO_INCREMENT NOT NULL,
  UUID_EVENTO CHAR(36) NOT NULL,
  UUID_CORRELACION CHAR(36) NULL,
  TIPO_EVENTO VARCHAR(80) NOT NULL,
  AGREGADO_TIPO VARCHAR(80) NOT NULL,
  AGREGADO_ID VARCHAR(80) NOT NULL,
  PAYLOAD_JSON JSON NOT NULL,
  ESTADO VARCHAR(20) NOT NULL DEFAULT 'PENDIENTE',
  INTENTOS INT NOT NULL DEFAULT 0,
  FECHA_CREACION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FECHA_PUBLICACION DATETIME NULL,
  ERROR_ULTIMO VARCHAR(1000) NULL,
  CONSTRAINT PK_OUTBOX_ACCOUNT PRIMARY KEY (ID),
  CONSTRAINT UK_OUTBOX_ACCOUNT_UUID UNIQUE (UUID_EVENTO),
  CONSTRAINT CK_OUTBOX_ACCOUNT_ESTADO CHECK (ESTADO IN ('PENDIENTE','PUBLICADO','ERROR','DESCARTADO'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Eventos confiables del account-service';

CREATE VIEW V_SALDO_CUENTA_RESUMEN AS
SELECT UUID_CUENTA, NUMERO_CUENTA, UUID_CLIENTE, IDENTIFICACION_TITULAR, NOMBRE_TITULAR_REFERENCIA,
       ESTADO, SALDO_CONTABLE, SALDO_DISPONIBLE, MONTO_RETENIDO,
       ES_CUENTA_MATRIZ_PAGOS, ES_CUENTA_FAVORITA_PAGOS, PROPOSITO_CUENTA
FROM CUENTA;

CREATE INDEX IDX_CUENTA_CLIENTE ON CUENTA(UUID_CLIENTE, ESTADO);
CREATE INDEX IDX_CUENTA_NUMERO_ESTADO ON CUENTA(NUMERO_CUENTA, ESTADO);
CREATE INDEX IDX_RESERVA_CORRELACION ON RESERVA_PAGO_MASIVO(UUID_CORRELACION);
CREATE INDEX IDX_INSTRUCCION_RESERVA ON INSTRUCCION_PAGO_MASIVO_CORE(RESERVA_PAGO_MASIVO_ID, ESTADO);
CREATE INDEX IDX_TRANSACCION_CUENTA_FECHA ON TRANSACCION_CUENTA(CUENTA_ID, FECHA_CONTABLE, TIMESTAMP_TRANSACCION);
CREATE INDEX IDX_TRANSACCION_CANAL ON TRANSACCION_CUENTA(CANAL_ORIGEN, FECHA_CONTABLE);
CREATE INDEX IDX_OUTBOX_ACCOUNT_ESTADO ON OUTBOX_EVENT(ESTADO, FECHA_CREACION);
CREATE INDEX IDX_IDEMPOTENCIA_EXPIRACION ON REGISTRO_IDEMPOTENCIA(ESTADO, FECHA_EXPIRACION);
