-- R9-D: liquidación delegada Core-Switch con fondeo global, consumo por línea,
-- comisión/IVA, liberación y trazabilidad financiera completa.
-- La migración es aditiva y tolera una ejecución DDL parcialmente confirmada.

DELIMITER $$

DROP PROCEDURE IF EXISTS align_mass_payment_settlement_schema$$
CREATE PROCEDURE align_mass_payment_settlement_schema()
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.COLUMNS
         WHERE TABLE_SCHEMA = DATABASE()
           AND TABLE_NAME = 'RESERVA_PAGO_MASIVO'
           AND COLUMN_NAME = 'MONTO_COMISION_COBRADO'
    ) THEN
        ALTER TABLE RESERVA_PAGO_MASIVO
            ADD COLUMN MONTO_COMISION_COBRADO DECIMAL(19,2) NOT NULL DEFAULT 0.00
            AFTER MONTO_COMISION;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM information_schema.COLUMNS
         WHERE TABLE_SCHEMA = DATABASE()
           AND TABLE_NAME = 'RESERVA_PAGO_MASIVO'
           AND COLUMN_NAME = 'UUID_TRANSACCION_FONDEO'
    ) THEN
        ALTER TABLE RESERVA_PAGO_MASIVO
            ADD COLUMN UUID_TRANSACCION_FONDEO CHAR(36) NULL
            AFTER ASIENTO_RESERVA_UUID;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM information_schema.COLUMNS
         WHERE TABLE_SCHEMA = DATABASE()
           AND TABLE_NAME = 'RESERVA_PAGO_MASIVO'
           AND COLUMN_NAME = 'FECHA_CIERRE'
    ) THEN
        ALTER TABLE RESERVA_PAGO_MASIVO
            ADD COLUMN FECHA_CIERRE DATETIME NULL
            AFTER FECHA_ACTUALIZACION;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM information_schema.COLUMNS
         WHERE TABLE_SCHEMA = DATABASE()
           AND TABLE_NAME = 'INSTRUCCION_PAGO_MASIVO_CORE'
           AND COLUMN_NAME = 'UUID_TRANSACCION_CORE'
    ) THEN
        ALTER TABLE INSTRUCCION_PAGO_MASIVO_CORE
            ADD COLUMN UUID_TRANSACCION_CORE CHAR(36) NULL
            AFTER MOTIVO_RECHAZO;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM information_schema.COLUMNS
         WHERE TABLE_SCHEMA = DATABASE()
           AND TABLE_NAME = 'INSTRUCCION_PAGO_MASIVO_CORE'
           AND COLUMN_NAME = 'ASIENTO_CONTABLE_UUID'
    ) THEN
        ALTER TABLE INSTRUCCION_PAGO_MASIVO_CORE
            ADD COLUMN ASIENTO_CONTABLE_UUID CHAR(36) NULL
            AFTER UUID_TRANSACCION_CORE;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM information_schema.COLUMNS
         WHERE TABLE_SCHEMA = DATABASE()
           AND TABLE_NAME = 'INSTRUCCION_PAGO_MASIVO_CORE'
           AND COLUMN_NAME = 'NUMERO_COMPROBANTE'
    ) THEN
        ALTER TABLE INSTRUCCION_PAGO_MASIVO_CORE
            ADD COLUMN NUMERO_COMPROBANTE VARCHAR(80) NULL
            AFTER ASIENTO_CONTABLE_UUID;
    END IF;


    IF NOT EXISTS (
        SELECT 1 FROM information_schema.STATISTICS
         WHERE TABLE_SCHEMA = DATABASE()
           AND TABLE_NAME = 'RESERVA_PAGO_MASIVO'
           AND INDEX_NAME = 'UK_RESERVA_PM_CORRELACION'
    ) THEN
        CREATE UNIQUE INDEX UK_RESERVA_PM_CORRELACION
            ON RESERVA_PAGO_MASIVO (UUID_CORRELACION);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM information_schema.TABLE_CONSTRAINTS
         WHERE CONSTRAINT_SCHEMA = DATABASE()
           AND TABLE_NAME = 'RESERVA_PAGO_MASIVO'
           AND CONSTRAINT_NAME = 'CK_RESERVA_PM_COMISION_COBRADA'
    ) THEN
        ALTER TABLE RESERVA_PAGO_MASIVO
            ADD CONSTRAINT CK_RESERVA_PM_COMISION_COBRADA
            CHECK (MONTO_COMISION_COBRADO >= 0
                   AND MONTO_COMISION_COBRADO <= MONTO_COMISION);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM information_schema.TABLE_CONSTRAINTS
         WHERE CONSTRAINT_SCHEMA = DATABASE()
           AND TABLE_NAME = 'RESERVA_PAGO_MASIVO'
           AND CONSTRAINT_NAME = 'CK_RESERVA_PM_DISTRIBUCION'
    ) THEN
        ALTER TABLE RESERVA_PAGO_MASIVO
            ADD CONSTRAINT CK_RESERVA_PM_DISTRIBUCION
            CHECK (MONTO_CONSUMIDO_ONUS + MONTO_CONSUMIDO_OFFUS
                   + MONTO_COMISION_COBRADO + MONTO_LIBERADO <= MONTO_RESERVADO);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM information_schema.STATISTICS
         WHERE TABLE_SCHEMA = DATABASE()
           AND TABLE_NAME = 'RESERVA_PAGO_MASIVO'
           AND INDEX_NAME = 'IDX_RESERVA_PM_CLIENTE_FECHA'
    ) THEN
        CREATE INDEX IDX_RESERVA_PM_CLIENTE_FECHA
            ON RESERVA_PAGO_MASIVO (UUID_CLIENTE_EMPRESA, FECHA_CONTABLE, ESTADO);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM information_schema.STATISTICS
         WHERE TABLE_SCHEMA = DATABASE()
           AND TABLE_NAME = 'INSTRUCCION_PAGO_MASIVO_CORE'
           AND INDEX_NAME = 'IDX_INSTRUCCION_PM_CORRELACION'
    ) THEN
        CREATE INDEX IDX_INSTRUCCION_PM_CORRELACION
            ON INSTRUCCION_PAGO_MASIVO_CORE (UUID_CORRELACION);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM information_schema.STATISTICS
         WHERE TABLE_SCHEMA = DATABASE()
           AND TABLE_NAME = 'INSTRUCCION_PAGO_MASIVO_CORE'
           AND INDEX_NAME = 'IDX_INSTRUCCION_PM_BATCH_ESTADO'
    ) THEN
        CREATE INDEX IDX_INSTRUCCION_PM_BATCH_ESTADO
            ON INSTRUCCION_PAGO_MASIVO_CORE (BATCH_ID_EXTERNO, ESTADO, FECHA_CREACION);
    END IF;
END$$

CALL align_mass_payment_settlement_schema()$$
DROP PROCEDURE align_mass_payment_settlement_schema$$

DELIMITER ;
