-- R9-H: trazabilidad de consistencia distribuida Account-Accounting.
-- No modifica saldos ni movimientos históricos. Agrega estado contable operacional
-- para permitir reconciliación segura ante timeout, respuesta perdida o indisponibilidad.

DELIMITER $$

DROP PROCEDURE IF EXISTS align_r9h_accounting_consistency_tracking$$
CREATE PROCEDURE align_r9h_accounting_consistency_tracking()
BEGIN
    IF NOT EXISTS (
        SELECT 1
          FROM information_schema.COLUMNS
         WHERE TABLE_SCHEMA = DATABASE()
           AND TABLE_NAME = 'TRANSACCION_CUENTA'
           AND COLUMN_NAME = 'ESTADO_CONTABILIZACION'
    ) THEN
        ALTER TABLE TRANSACCION_CUENTA
            ADD COLUMN ESTADO_CONTABILIZACION VARCHAR(40) NOT NULL DEFAULT 'PENDIENTE_CONTABILIDAD'
            AFTER ASIENTO_CONTABLE_UUID;
    END IF;

    IF NOT EXISTS (
        SELECT 1
          FROM information_schema.COLUMNS
         WHERE TABLE_SCHEMA = DATABASE()
           AND TABLE_NAME = 'TRANSACCION_CUENTA'
           AND COLUMN_NAME = 'FECHA_CONTABILIZACION'
    ) THEN
        ALTER TABLE TRANSACCION_CUENTA
            ADD COLUMN FECHA_CONTABILIZACION DATETIME NULL
            AFTER ESTADO_CONTABILIZACION;
    END IF;

    IF NOT EXISTS (
        SELECT 1
          FROM information_schema.COLUMNS
         WHERE TABLE_SCHEMA = DATABASE()
           AND TABLE_NAME = 'TRANSACCION_CUENTA'
           AND COLUMN_NAME = 'CODIGO_ERROR_CONTABLE'
    ) THEN
        ALTER TABLE TRANSACCION_CUENTA
            ADD COLUMN CODIGO_ERROR_CONTABLE VARCHAR(80) NULL
            AFTER FECHA_CONTABILIZACION;
    END IF;

    IF NOT EXISTS (
        SELECT 1
          FROM information_schema.COLUMNS
         WHERE TABLE_SCHEMA = DATABASE()
           AND TABLE_NAME = 'TRANSACCION_CUENTA'
           AND COLUMN_NAME = 'MENSAJE_ERROR_CONTABLE'
    ) THEN
        ALTER TABLE TRANSACCION_CUENTA
            ADD COLUMN MENSAJE_ERROR_CONTABLE VARCHAR(500) NULL
            AFTER CODIGO_ERROR_CONTABLE;
    END IF;

    UPDATE TRANSACCION_CUENTA
       SET ESTADO_CONTABILIZACION = 'CONTABILIZADA',
           FECHA_CONTABILIZACION = COALESCE(FECHA_CONTABILIZACION, TIMESTAMP_TRANSACCION),
           CODIGO_ERROR_CONTABLE = NULL,
           MENSAJE_ERROR_CONTABLE = NULL
     WHERE ASIENTO_CONTABLE_UUID IS NOT NULL
       AND ASIENTO_CONTABLE_UUID <> ''
       AND ESTADO_CONTABILIZACION <> 'CONTABILIZADA';

    UPDATE TRANSACCION_CUENTA
       SET ESTADO_CONTABILIZACION = 'PENDIENTE_CONTABILIDAD'
     WHERE (ASIENTO_CONTABLE_UUID IS NULL OR ASIENTO_CONTABLE_UUID = '')
       AND ESTADO_CONTABILIZACION IS NULL;

    IF NOT EXISTS (
        SELECT 1
          FROM information_schema.STATISTICS
         WHERE TABLE_SCHEMA = DATABASE()
           AND TABLE_NAME = 'TRANSACCION_CUENTA'
           AND INDEX_NAME = 'IX_TX_CUENTA_ESTADO_CONTABILIZACION'
    ) THEN
        CREATE INDEX IX_TX_CUENTA_ESTADO_CONTABILIZACION
            ON TRANSACCION_CUENTA (ESTADO_CONTABILIZACION, FECHA_CREACION);
    END IF;

    IF NOT EXISTS (
        SELECT 1
          FROM information_schema.STATISTICS
         WHERE TABLE_SCHEMA = DATABASE()
           AND TABLE_NAME = 'TRANSACCION_CUENTA'
           AND INDEX_NAME = 'IX_TX_CUENTA_ASIENTO_CONTABLE_UUID'
    ) THEN
        CREATE INDEX IX_TX_CUENTA_ASIENTO_CONTABLE_UUID
            ON TRANSACCION_CUENTA (ASIENTO_CONTABLE_UUID);
    END IF;
END$$

CALL align_r9h_accounting_consistency_tracking()$$
DROP PROCEDURE align_r9h_accounting_consistency_tracking$$

DELIMITER ;
